baseurl = "haiduongnguyen.github.io"
title = "Hai Duong Nguyen"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/bg.jpg"
  title = "Software Engineering"
  slogan = "Dream need action to be come life"
  SEOTitle = "Data Engineering"
  keyword = "Data, Python, Life, Science, Gosship"
 
  # Sidebar settings
  sidebar_about_description = ""
  sidebar_avatar = "images/nature.jpg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "haiduong667799@gmail.com"
  linkedin       = "https://www.linkedin.com/in/nguyen-hai-duong-1a34a71ba/"
  github         = "https://github.com/haiduongnguyen"